### PR TITLE
fix bug when MenuItemView is not visible,it's onClick event still can…

### PR DESCRIPTION
**Pull request by brucetoo**
fix bug when MenuItemView is not visible,it's onClick event still can work

### CODE REVIEW

**Comment by rgdevment** [comment]
hi, how use in gradle this commit on android studio?

thxs

**Comment by brucetoo** [comment]
Use Github itself...

**Comment by rgdevment** [comment]
cant helpme plz?

compile 'com.brucetoo.springfloatingactionmenu:library:0.0.1' not found :(

**Comment by pishguy** [comment]
i have this same problem now.

**Comment by brucetoo** [comment]
@tux-world and @MarioTi  I did not upload code to Jcenter,so `com.brucetoo.springfloatingactionmenu:library:0.0.1` is not available ...Wait tiancaiCC to accept this PR and upload to Jcenter

**Comment by pishguy** [comment]
@brucetoo could you help me to who to resolve this problem? i downloaded library source code, but i cant find which file and method must be update. thanks

**Comment by brucetoo** [comment]
@tux-world  you can use [This](https://github.com/brucetoo/SpringFloatingActionMenu) source code instead

**Comment by pishguy** [comment]
@brucetoo i download and test your last commit, its not resolve problem sir, after close it, i must be multiple click on other view to work and `ClickListener` work still after close that

**Comment by brucetoo** [comment]
@tux-world  what do you mean "i must be multiple click on other view to work". when open,MenuItemView is clickable  but is not clickable when close...thats what i did

**Comment by pishguy** [comment]
​​
​Your code doesn't work correctly, would you like to see demo of my
application, maybe you know whats problem

**Comment by brucetoo** [comment]
show me the apk.

**Comment by pishguy** [comment]
i dont upload Nodejs on server and apk don't work correctly on your phone,
i'm recording before and after using this library, wait to upload and
sending link for you

**Comment by pishguy** [comment]
​Before using this library http://www.pishguy.com/files/Before.mp4

After Using That, in this video you can see i must be multiple click on
other view to work http://www.pishguy.com/files/After.mp4

**Comment by brucetoo** [comment]
I know what you mean,wait me to fix it

**Comment by brucetoo** [comment]
@tux-world  please check out the new fix (https://github.com/tiancaiCC/SpringFloatingActionMenu/pull/14)

**Comment by pishguy** [comment]
@brucetoo after click outside of this library icons. underneath widgets such as any textview or clickable linearlayout can click, why?

**Comment by m16u31D** [comment]
Hi @brucetoo  thanks for your work, but I have the same problem this is my apk http://expirebox.com/download/aca72586e72ee4b53864a8b022085656.html

**Comment by pishguy** [comment]
@elsuper-migueld please explain whats your problem, i downloaded your file and install on my phone but i dont know whats problem

**Comment by m16u31D** [comment]
Hi @tux-world the problem is the menu is invisible but I can touch the menu items/buttons and show the Toasts messages, please try to move between the tabs if you try to move you are going to press the "hidden" buttons / menu items

**Comment by pishguy** [comment]
i had this problem too,

@amanzan said to me: 

> If you open SpringFloatingActionMenu.java and add "view.setClickable(true);" in line 355, problem is fixed

and my problem resolved.

**Pull request merged**
