### PR TITLE
Fix bug when menu is invisible and still hold the touch event

### PR DESCRIPTION
**Pull request by brucetoo**

### CODE REVIEW

**Comment by pishguy** [comment]
@brucetoo thanks. problem resolved, how can i disable moving SpringFloatingActionBar?

**Comment by brucetoo** [comment]
@tux-world  you should read the source code and try it yourself intead asking someone directly

**Comment by pishguy** [comment]
This library has many bug which don't resolved and unfortunately we can't use that

**Comment by pishguy** [comment]
@tiancaiCC problem for clicked on below widgets doesnt resolved :-1:

**Comment by lusccc** [comment]
@tux-world this weekend, i will fix some bugs. 

## sorry

**Pull request merged**
